#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Cargo")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Datos.Properties.Settings.Default.CargoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.prc_slcPersona")]
		public ISingleResult<prc_slcPersonaResult> prc_slcPersona([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codigo_persona, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string p_nombres, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string p_contacto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string p_pais)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codigo_persona, p_nombres, p_contacto, p_pais);
			return ((ISingleResult<prc_slcPersonaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.prc_slcTipo")]
		public ISingleResult<prc_slcTipoResult> prc_slcTipo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codigo_tipo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codigo_tipo);
			return ((ISingleResult<prc_slcTipoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.prc_slcPuerto")]
		public ISingleResult<prc_slcPuertoResult> prc_slcPuerto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codigo_puerto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codigo_pais, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_puerto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codigo_puerto, p_codigo_pais, p_puerto);
			return ((ISingleResult<prc_slcPuertoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.prc_insPersona")]
		public int prc_insPersona(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string p_nombres, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codigo_pais, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codigo_puerto, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codigo_tipo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_marca, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string p_contacto, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string p_estado, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string p_ciudad, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string p_direccion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_telefono, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_fax, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string p_email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string p_direccion2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_telefono2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_fax2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string p_email2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_zip, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_creado_por)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_nombres, p_codigo_pais, p_codigo_puerto, p_codigo_tipo, p_marca, p_contacto, p_estado, p_ciudad, p_direccion, p_telefono, p_fax, p_email, p_direccion2, p_telefono2, p_fax2, p_email2, p_zip, p_creado_por);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.prc_updPersona")]
		public int prc_updPersona(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codigo_persona, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string p_nombres, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codigo_pais, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codigo_puerto, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codigo_tipo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_marca, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string p_contacto, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string p_estado, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string p_ciudad, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string p_direccion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_telefono, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_fax, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string p_email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string p_direccion2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_telefono2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_fax2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string p_email2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_zip, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_modificado_por)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codigo_persona, p_nombres, p_codigo_pais, p_codigo_puerto, p_codigo_tipo, p_marca, p_contacto, p_estado, p_ciudad, p_direccion, p_telefono, p_fax, p_email, p_direccion2, p_telefono2, p_fax2, p_email2, p_zip, p_modificado_por);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.prc_delPersona")]
		public int prc_delPersona([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codigo_persona)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codigo_persona);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class prc_slcPersonaResult
	{
		
		private decimal _N_CODIGO_PERSONA;
		
		private string _C_NOMBRES;
		
		private System.Nullable<decimal> _N_CODIGO_PAIS;
		
		private string _C_PAIS;
		
		private System.Nullable<decimal> _N_CODIGO_PUERTO;
		
		private string _C_PUERTO;
		
		private System.Nullable<decimal> _N_CODIGO_TIPO;
		
		private string _C_TIPO;
		
		private string _C_MARCA;
		
		private string _C_CONTACTO;
		
		private string _C_ESTADO;
		
		private string _C_CIUDAD;
		
		private string _C_DIRECCION;
		
		private string _C_TELEFONO;
		
		private string _C_FAX;
		
		private string _C_EMAIL;
		
		private string _C_DIRECCION2;
		
		private string _C_TELEFONO2;
		
		private string _C_FAX2;
		
		private string _C_EMAIL2;
		
		private string _C_ZIP;
		
		public prc_slcPersonaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_CODIGO_PERSONA", DbType="Decimal(18,0) NOT NULL")]
		public decimal N_CODIGO_PERSONA
		{
			get
			{
				return this._N_CODIGO_PERSONA;
			}
			set
			{
				if ((this._N_CODIGO_PERSONA != value))
				{
					this._N_CODIGO_PERSONA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_NOMBRES", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string C_NOMBRES
		{
			get
			{
				return this._C_NOMBRES;
			}
			set
			{
				if ((this._C_NOMBRES != value))
				{
					this._C_NOMBRES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_CODIGO_PAIS", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> N_CODIGO_PAIS
		{
			get
			{
				return this._N_CODIGO_PAIS;
			}
			set
			{
				if ((this._N_CODIGO_PAIS != value))
				{
					this._N_CODIGO_PAIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_PAIS", DbType="VarChar(100)")]
		public string C_PAIS
		{
			get
			{
				return this._C_PAIS;
			}
			set
			{
				if ((this._C_PAIS != value))
				{
					this._C_PAIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_CODIGO_PUERTO", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> N_CODIGO_PUERTO
		{
			get
			{
				return this._N_CODIGO_PUERTO;
			}
			set
			{
				if ((this._N_CODIGO_PUERTO != value))
				{
					this._N_CODIGO_PUERTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_PUERTO", DbType="VarChar(50)")]
		public string C_PUERTO
		{
			get
			{
				return this._C_PUERTO;
			}
			set
			{
				if ((this._C_PUERTO != value))
				{
					this._C_PUERTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_CODIGO_TIPO", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> N_CODIGO_TIPO
		{
			get
			{
				return this._N_CODIGO_TIPO;
			}
			set
			{
				if ((this._N_CODIGO_TIPO != value))
				{
					this._N_CODIGO_TIPO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_TIPO", DbType="VarChar(100)")]
		public string C_TIPO
		{
			get
			{
				return this._C_TIPO;
			}
			set
			{
				if ((this._C_TIPO != value))
				{
					this._C_TIPO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_MARCA", DbType="VarChar(50)")]
		public string C_MARCA
		{
			get
			{
				return this._C_MARCA;
			}
			set
			{
				if ((this._C_MARCA != value))
				{
					this._C_MARCA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_CONTACTO", DbType="VarChar(200)")]
		public string C_CONTACTO
		{
			get
			{
				return this._C_CONTACTO;
			}
			set
			{
				if ((this._C_CONTACTO != value))
				{
					this._C_CONTACTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_ESTADO", DbType="VarChar(200)")]
		public string C_ESTADO
		{
			get
			{
				return this._C_ESTADO;
			}
			set
			{
				if ((this._C_ESTADO != value))
				{
					this._C_ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_CIUDAD", DbType="VarChar(100)")]
		public string C_CIUDAD
		{
			get
			{
				return this._C_CIUDAD;
			}
			set
			{
				if ((this._C_CIUDAD != value))
				{
					this._C_CIUDAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_DIRECCION", DbType="VarChar(200)")]
		public string C_DIRECCION
		{
			get
			{
				return this._C_DIRECCION;
			}
			set
			{
				if ((this._C_DIRECCION != value))
				{
					this._C_DIRECCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_TELEFONO", DbType="VarChar(50)")]
		public string C_TELEFONO
		{
			get
			{
				return this._C_TELEFONO;
			}
			set
			{
				if ((this._C_TELEFONO != value))
				{
					this._C_TELEFONO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_FAX", DbType="VarChar(50)")]
		public string C_FAX
		{
			get
			{
				return this._C_FAX;
			}
			set
			{
				if ((this._C_FAX != value))
				{
					this._C_FAX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_EMAIL", DbType="VarChar(100)")]
		public string C_EMAIL
		{
			get
			{
				return this._C_EMAIL;
			}
			set
			{
				if ((this._C_EMAIL != value))
				{
					this._C_EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_DIRECCION2", DbType="VarChar(200)")]
		public string C_DIRECCION2
		{
			get
			{
				return this._C_DIRECCION2;
			}
			set
			{
				if ((this._C_DIRECCION2 != value))
				{
					this._C_DIRECCION2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_TELEFONO2", DbType="VarChar(50)")]
		public string C_TELEFONO2
		{
			get
			{
				return this._C_TELEFONO2;
			}
			set
			{
				if ((this._C_TELEFONO2 != value))
				{
					this._C_TELEFONO2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_FAX2", DbType="VarChar(50)")]
		public string C_FAX2
		{
			get
			{
				return this._C_FAX2;
			}
			set
			{
				if ((this._C_FAX2 != value))
				{
					this._C_FAX2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_EMAIL2", DbType="VarChar(100)")]
		public string C_EMAIL2
		{
			get
			{
				return this._C_EMAIL2;
			}
			set
			{
				if ((this._C_EMAIL2 != value))
				{
					this._C_EMAIL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_ZIP", DbType="VarChar(50)")]
		public string C_ZIP
		{
			get
			{
				return this._C_ZIP;
			}
			set
			{
				if ((this._C_ZIP != value))
				{
					this._C_ZIP = value;
				}
			}
		}
	}
	
	public partial class prc_slcTipoResult
	{
		
		private decimal _N_CODIGO_TIPO;
		
		private string _C_TIPO;
		
		public prc_slcTipoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_CODIGO_TIPO", DbType="Decimal(18,0) NOT NULL")]
		public decimal N_CODIGO_TIPO
		{
			get
			{
				return this._N_CODIGO_TIPO;
			}
			set
			{
				if ((this._N_CODIGO_TIPO != value))
				{
					this._N_CODIGO_TIPO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_TIPO", DbType="VarChar(100)")]
		public string C_TIPO
		{
			get
			{
				return this._C_TIPO;
			}
			set
			{
				if ((this._C_TIPO != value))
				{
					this._C_TIPO = value;
				}
			}
		}
	}
	
	public partial class prc_slcPuertoResult
	{
		
		private decimal _N_CODIGO_PUERTO;
		
		private string _C_PUERTO;
		
		private System.Nullable<decimal> _N_CODIGO_PAIS;
		
		private string _C_PUERTO_PAIS;
		
		public prc_slcPuertoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_CODIGO_PUERTO", DbType="Decimal(18,0) NOT NULL")]
		public decimal N_CODIGO_PUERTO
		{
			get
			{
				return this._N_CODIGO_PUERTO;
			}
			set
			{
				if ((this._N_CODIGO_PUERTO != value))
				{
					this._N_CODIGO_PUERTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_PUERTO", DbType="VarChar(50)")]
		public string C_PUERTO
		{
			get
			{
				return this._C_PUERTO;
			}
			set
			{
				if ((this._C_PUERTO != value))
				{
					this._C_PUERTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_CODIGO_PAIS", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> N_CODIGO_PAIS
		{
			get
			{
				return this._N_CODIGO_PAIS;
			}
			set
			{
				if ((this._N_CODIGO_PAIS != value))
				{
					this._N_CODIGO_PAIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_PUERTO_PAIS", DbType="VarChar(153)")]
		public string C_PUERTO_PAIS
		{
			get
			{
				return this._C_PUERTO_PAIS;
			}
			set
			{
				if ((this._C_PUERTO_PAIS != value))
				{
					this._C_PUERTO_PAIS = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
